# Generated by Django 6.0.1 on 2026-02-02 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_personalprofile'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
