# Generated by Django 6.0.1 on 2026-02-02 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_personalprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Counties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GameMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Solo', 'Solo'), ('Team', 'Team'), ('Duo', 'Duo'), ('Squad', 'Squad')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('icon', models.CharField(blank=True, help_text='CSS class for icon (e.g. fa-users)', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('closes_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('running', 'Running'), ('registration_ongoing', 'Registration Ongoing'), ('completed', 'Completed')], default='upcoming', max_length=20)),
                ('is_open_to_join', models.BooleanField(default=True)),
                ('participants', models.ManyToManyField(related_name='cohort_participants', to='users.personalprofile')),
            ],
        ),
        migrations.CreateModel(
            name='GameStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of the stage in a competition')),
                ('game_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='home.gamemode')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateTimeField()),
                ('cohort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fixture_cohort', to='home.cohort')),
                ('players', models.ManyToManyField(related_name='fixtures', to=settings.AUTH_USER_MODEL)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixtures', to='home.gamestage')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateTimeField()),
                ('cohort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cohort', to='home.cohort')),
                ('participants', models.ManyToManyField(related_name='rounds', to=settings.AUTH_USER_MODEL)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='home.gamestage')),
            ],
        ),
        migrations.CreateModel(
            name='RoundPlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('kills', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('xp', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to=settings.AUTH_USER_MODEL)),
                ('round_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamup_stats', to='home.round')),
            ],
        ),
        migrations.CreateModel(
            name='TeamUP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('captain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captain', to=settings.AUTH_USER_MODEL)),
                ('game_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamups', to='home.gamemode')),
                ('players', models.ManyToManyField(related_name='teamups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StageParticipants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants_cohort', to='home.cohort')),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant_stage', to='users.personalprofile')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_participants', to='home.gamestage')),
                ('teamup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teamup_stage', to='home.teamup')),
            ],
        ),
        migrations.AddField(
            model_name='cohort',
            name='teamups',
            field=models.ManyToManyField(related_name='cohort_teamups', to='home.teamup'),
        ),
        migrations.CreateModel(
            name='TeamUPFixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateTimeField()),
                ('cohort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teamup_fixture_cohort', to='home.cohort')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamup_fixtures', to='home.gamestage')),
                ('teamups', models.ManyToManyField(related_name='teamup_fixtures', to='home.teamup')),
            ],
        ),
        migrations.CreateModel(
            name='TeamUPRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateTimeField()),
                ('cohort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teamup_cohort', to='home.cohort')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamup_rounds', to='home.gamestage')),
                ('teamup', models.ManyToManyField(related_name='teamup_rounds', to='home.teamup')),
            ],
        ),
        migrations.CreateModel(
            name='TeamUPRoundStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('kills', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('xp', models.IntegerField()),
                ('round_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_stats', to='home.teamupround')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_round_stats', to='home.teamup')),
            ],
        ),
    ]
