# Generated by Django 6.0.1 on 2026-02-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundplayerstats',
            name='damage',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='roundplayerstats',
            name='time_alive',
            field=models.CharField(blank=True, help_text='e.g. 12:45', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teamuproundstats',
            name='damage',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
