# Generated by Django 6.0.1 on 2026-02-02 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_roundplayerstats_damage_roundplayerstats_time_alive_and_more'),
        ('users', '0004_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, related_name='cohort_participants', to='users.personalprofile'),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='teamups',
            field=models.ManyToManyField(blank=True, related_name='cohort_teamups', to='home.teamup'),
        ),
    ]
