# Generated by Django 6.0.1 on 2026-02-02 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_cohort_participants_alter_cohort_teamups'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='fixture',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='round_result', to='home.fixture'),
        ),
        migrations.AddField(
            model_name='teamupround',
            name='fixture',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='round_result', to='home.teamupfixture'),
        ),
    ]
