# Generated by Django 6.0.1 on 2026-02-02 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_round_fixture_teamupround_fixture'),
        ('users', '0005_personalprofile_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='cohort_participants', to='users.personalprofile'),
        ),
        migrations.AlterField(
            model_name='teamuproundstats',
            name='deaths',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamuproundstats',
            name='kills',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamuproundstats',
            name='xp',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='TeamUPPlayerRoundStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kills', models.IntegerField(default=0)),
                ('deaths', models.IntegerField(default=0)),
                ('damage', models.IntegerField(default=0)),
                ('xp', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_player_stats', to=settings.AUTH_USER_MODEL)),
                ('round_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_team_stats', to='home.teamupround')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_match_stats', to='home.teamup')),
            ],
        ),
    ]
