# Generated by Django 4.2.27 on 2026-02-03 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_gamestage_is_final_alter_cohort_id_alter_counties_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemode',
            name='max_players',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
