# Generated by Django 4.2.27 on 2026-02-03 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_mpesatransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesatransaction',
            name='game_mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_transactions', to='home.gamemode'),
        ),
    ]
