# Generated by Django 4.2.27 on 2026-02-03 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_mpesatransaction_game_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesatransaction',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_transactions', to='home.teamup'),
        ),
    ]
